//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class talent
    {
        public Nullable<int> id { get; set; }
        public string equipment { get; set; }
        public string description { get; set; }
        public int experience { get; set; }
    
        public virtual profile profile { get; set; }
    }
}
