//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collaborations
    {
        public collaborations()
        {
            this.collaborationfiles = new HashSet<collaborationfiles>();
            this.talentwanted = new HashSet<talentwanted>();
        }
    
        public Nullable<int> profileId { get; set; }
        public int colid { get; set; }
        public string ColName { get; set; }
        public string genre { get; set; }
        public string colOwner { get; set; }
        public byte[] ColFile { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual ICollection<collaborationfiles> collaborationfiles { get; set; }
        public virtual ICollection<talentwanted> talentwanted { get; set; }
    }
}
