//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class talentwanted
    {
        public Nullable<int> colkey { get; set; }
        public string twantedName { get; set; }
        public Nullable<int> tID { get; set; }
    
        public virtual collaborations collaborations { get; set; }
        public virtual talent talent { get; set; }
    }
}
