//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collaborationfiles
    {
        public int collaborationFileId { get; set; }
        public Nullable<int> collaborationID { get; set; }
        public byte[] collaborationFile { get; set; }
    
        public virtual collaborations collaborations { get; set; }
    }
}
